CREATE TABLE KATEGORIE_ZAROBKOWE
(
    id INT IDENTITY PRIMARY KEY,
    kategoria_zarobkowa VARCHAR(20) NOT NULL,
);

CREATE TABLE STANY_CYWILNE
(
    id INT IDENTITY PRIMARY KEY,
    stan_cywilny VARCHAR(20) NOT NULL,
);

CREATE TABLE KLIENCI
(
    id INT IDENTITY PRIMARY KEY,
	imie VARCHAR(50),
	nazwisko VARCHAR(50) NOT NULL,
	adres VARCHAR(60) NOT NULL,
	PESEL VARCHAR(20) NOT NULL,
	telefon VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	nr_dowodu VARCHAR(20) NOT NULL,
	id_kategorii_zarobkowej INT REFERENCES KATEGORIE_ZAROBKOWE,
	id_stanu_cywilnego INT REFERENCES STANY_CYWILNE
);

CREATE TABLE KRAJE
(
	id INT IDENTITY PRIMARY KEY,
	nazwa_kraju VARCHAR(50) NOT NULL
);

CREATE TABLE UMOWY
(
	id INT IDENTITY PRIMARY KEY,
	data DATE NOT NULL,
	id_klienta INT NOT NULL REFERENCES Klienci
);

CREATE TABLE PLATNOSCI
(
	id INT IDENTITY PRIMARY KEY,
	kwota DECIMAL(10,2) NOT NULL,
	data DATE NOT NULL,
	typ VARCHAR(20) NOT NULL,
	id_umowy INT NOT NULL REFERENCES Umowy
);

CREATE TABLE OPERATORZY
(
	id INT IDENTITY PRIMARY KEY,
	nazwa_firmy VARCHAR(50) NOT NULL,
	telefon VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL
);
CREATE TABLE SIECI_HOTELI
(
	id INT IDENTITY PRIMARY KEY,
	nazwa_sieci VARCHAR(50) NOT NULL
);

CREATE TABLE HOTELE
(
	id INT IDENTITY PRIMARY KEY,
	adres VARCHAR(60),
	email VARCHAR(50),
	telefon VARCHAR(20),
	id_kraju INT NOT NULL REFERENCES KRAJE,
	id_sieci_hotelu INT REFERENCES SIECI_HOTELI
);

CREATE TABLE WYCIECZKI
(
	id INT IDENTITY PRIMARY KEY,
	cena DECIMAL(10,2),
	data_rozpoczecia DATE NOT NULL,
	data_zakonczenia DATE NOT NULL,
	id_operatora INT NOT NULL REFERENCES OPERATORZY,
	id_umowy INT NO  NULL REFERENCES UMOWY,
	id_hotelu INT NOT NULL REFERENCES HOTELE
);

