DROP TABLE IF EXISTS dbo.WYCIECZKI;
DROP TABLE IF EXISTS dbo.PLATNOSCI;
DROP TABLE IF EXISTS dbo.UMOWY;
DROP TABLE IF EXISTS dbo.HOTELE;
DROP TABLE IF EXISTS dbo.SIECI_HOTELI;
DROP TABLE IF EXISTS dbo.KRAJE;
DROP TABLE IF EXISTS dbo.KLIENCI;
DROP TABLE IF EXISTS dbo.OPERATORZY;
DROP TABLE IF EXISTS dbo.KATEGORIE_ZAROBKOWE;
DROP TABLE IF EXISTS dbo.STANY_CYWILNE;
DROP TABLE IF EXISTS dbo.AuditTable;

DROP FUNCTION IF EXISTS wycieczkiOperatorowCenaWiekszaOd;
DROP FUNCTION IF EXISTS wycieczkiOperatorowCzasTrwania;
DROP FUNCTION IF EXISTS przychodOperatora;
DROP FUNCTION IF EXISTS liczbaSprzedanychWycieczekOperatora;
DROP FUNCTION IF EXISTS liczbaKupionychWycieczekKlienta;
GO

DROP PROCEDURE IF EXISTS updateKLIENT;
DROP PROCEDURE IF EXISTS updateHOTEL;
DROP PROCEDURE IF EXISTS updateWYCIECZKA;
DROP PROCEDURE IF EXISTS updateOPERATOR;
DROP PROCEDURE IF EXISTS updateSIECI_HOTELI;
DROP PROCEDURE IF EXISTS updateKRAJ;
GO

DROP VIEW IF EXISTS HOTELE_VIEW;
DROP VIEW IF EXISTS WYCIECZKI_KRAJE_VIEW;
DROP VIEW IF EXISTS WYCIECZKI_KLIENCI_VIEW;
DROP VIEW IF EXISTS WYCIECZKI_OPERATOROW;
DROP VIEW IF EXISTS KLIENCI_VIEW;
GO

