SELECT * FROM WYCIECZKI
FOR XML PATH ('WYCIECZKA');
   
SELECT * FROM PLATNOSCI
FOR XML PATH ('PLATNOSC');
   
SELECT * FROM UMOWY
FOR XML PATH ('UMOWA');
   
SELECT * FROM HOTELE
FOR XML PATH ('HOTEL');
   
SELECT * FROM SIECI_HOTELI
FOR XML PATH ('SIEC_HOTELI');
   
SELECT * FROM KRAJE
FOR XML PATH ('KRAJ');
   
SELECT * FROM OPERATORZY
FOR XML PATH ('OPERATOR');
   
SELECT * FROM KATEGORIE_ZAROBKOWE
FOR XML PATH ('KATEGORIA_ZAROBKOWA');
   
SELECT * FROM STANY_CYWILNE
FOR XML PATH ('STAN_CYWILNY');
   